apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudl-server-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudl-server
  template:
    metadata:
      labels:
        app: cloudl-server
    spec:
      containers:
        - name: cloudl-server
          image: "{{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}"
          ports:
            - containerPort: {{ .Values.service.backend.port }}
              name: nodejs-port
          env:
            - name: ME_CONFIG_MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  key: ME_CONFIG_MONGODB_URL
                  name: cloudl-configmap
                  optional: false
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  key: mongo-root-username
                  name: cloudl-secret
                  optional: false
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongo-root-password
                  name: cloudl-secret
                  optional: false
---
apiVersion: v1
kind: Service
metadata:
  name: cloudl-server-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: {{ .Values.service.backend.port }}
  selector:
    app: cloudl-server
