apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudl-server-deployment
spec:
  template:
    spec:
      containers:
        - name: cloudl-server
          image: awabahmed/cloudl:backendv2
