# elasticsearch-backup-cronjob.yml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: elasticsearch-backup
  namespace: default
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: curlimages/curl
            env:
            - name: ES_HOST
              value: "elasticsearch:9200"
            - name: SNAPSHOT_NAME
              value: "snapshot-$(date +%Y%m%d-%H%M%S)"
            command:
            - /bin/sh
            - -c
            - |
              # Register S3 repository
              curl -X PUT "$ES_HOST/_snapshot/my_s3_repository" -H 'Content-Type: application/json' -d'
              {
                "type": "s3",
                "settings": {
                  "bucket": "cloudl-efs-poc",
                  "region": "eu-north-1"
                }
              }'
              
              # Create snapshot
              curl -X PUT "$ES_HOST/_snapshot/my_s3_repository/$SNAPSHOT_NAME?wait_for_completion=true"
              
              # Cleanup old snapshots (keep last 7)
              curl -X GET "$ES_HOST/_snapshot/my_s3_repository/_all" | grep -o '"snapshot":"[^"]*"' | cut -d'"' -f4 | sort | head -n -7 | xargs -I {} curl -X DELETE "$ES_HOST/_snapshot/my_s3_repository/{}"
            volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws
          restartPolicy: OnFailure
          volumes:
          - name: aws-credentials
            secret:
              secretName: aws-s3-credentials
