# fluentd-daemonset-s3.yml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-s3
  namespace: default
  labels:
    app: fluentd-s3
    logging: "true"
spec:
  selector:
    matchLabels:
      app: fluentd-s3
  template:
    metadata:
      labels:
        app: fluentd-s3
        logging: "true"
    spec:
      serviceAccountName: fluentd
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: fluentd-s3
        image: fluent/fluentd-kubernetes-daemonset:v1.19-debian-s3-1
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-s3-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-s3-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: S3_BUCKET
          value: "cloudl-efs-poc"
        - name: S3_REGION
          value: "eu-north-1"
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-s3-config
          mountPath: /fluentd/etc/fluent.conf
          subPath: fluent.conf
        - name: fluentd-pos
          mountPath: /var/log/pos
        - name: fluentd-s3-buffer
          mountPath: /var/log/fluentd/s3
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-s3-config
        configMap:
          name: fluentd-s3-config
      - name: fluentd-pos
        emptyDir: {}
      - name: fluentd-s3-buffer
        emptyDir: {}
