apiVersion: v1
kind: Service
metadata:
  name: cloudl-server-service
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: cloudl-server
---
apiVersion: v1
kind: Service
metadata:
  name: cloudl-client-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-port
      nodePort: {{ .Values.service.client.nodePort }}
  selector:
    app: cloudl-client
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
spec:
  selector:
    app: mongodb-express
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: {{ .Values.service.mongoExpress.nodePort }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb
